name: Resumidor Diario de Noticias
on:
  schedule:
    - cron: "0 13 * * *"
    - cron: "0 17 * * *"
    - cron: "0 21 * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Instalar dependencias
        run: |
          pip install google-genai groq requests feedparser PyPDF2 python-dotenv
      - name: Executar Script
        env:
          GEMINI_KEY: ${{ secrets.GEMINI_KEY }}
          GROQ_KEY: ${{ secrets.GROQ_KEY }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          CARTEIRA: ${{ secrets.CARTEIRA }}
        run: python main.py
